version: 0.2

phases:
  install:
    runtime-versions:
      android: 29
      java: openjdk8
  build:
    commands:
      - chmod +x ./gradlew
      - ./gradlew assembleDebug
  post_build:
    commands:
      - ls -R
artifacts:
  files:
     - './app/build/outputs/apk/app-debug.apk'
  discard-paths: yes